# Shell variables
# Generated by 'wal'
wallpaper='/home/user/wallpapers/nice.jpg'

# Special
background='#20191f'
foreground='#d0dfe4'
cursor='#d0dfe4'

# Colors
color0='#20191f'
color1='#6B857B'
color2='#A37E82'
color3='#76948E'
color4='#93A5A3'
color5='#D0B4B1'
color6='#B2C9CC'
color7='#d0dfe4'
color8='#919c9f'
color9='#6B857B'
color10='#A37E82'
color11='#76948E'
color12='#93A5A3'
color13='#D0B4B1'
color14='#B2C9CC'
color15='#d0dfe4'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
